package deepequal

import "github.com/sirkon/deepequal/internal/reflect"

// Equal makes a deep equality comparison of given entities with a special care of types generated by
// protoc-gen-go.
func Equal(x, y any) bool {
	return reflect.DeepEqual(x, y)
}
